services:
    app.page_entity_listener:
        class: AppBundle\EntityListener\PageListener
        arguments: ['@service_container']
        tags:
#            - { name: doctrine.orm.entity_listener }
            - { name: doctrine.event_listener, event: postSoftDelete }
