services:
    app.page.manager:
        class: AppBundle\Manager\PageManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@page.repository"
            - "@monolog.logger"
