services:
    app.client.monitoring_resource:
        class: AppBundle\Service\Client\MonitoringResourceClient
        arguments:
            - "@guzzle.client.monitoring_resource"

    app.matching:
        class: AppBundle\Service\MatchingService
        arguments:
            - "@doctrine.orm.entity_manager"

    app.monitoring_resource:
        class: AppBundle\Service\MonitoringResourceService
        arguments:
            - "@app.monitoring_resource.manager"
