services:
    app.client.monitoring_resource:
        class: AppBundle\Service\Client\MonitoringResourceClient
        arguments:
            - "@guzzle.client.monitoring_resource"

    app.monitoring_resource:
        class: AppBundle\Service\MonitoringResourceService
        arguments:
            - "@app.monitoring_resource.manager"
